// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbeRHIQZkihAXVoprt7YNYB9DbXn8h0d0',
    appId: '1:377438843224:web:7644c81e2da8805edf752d',
    messagingSenderId: '377438843224',
    projectId: 'codequest-f1c8d',
    authDomain: 'codequest-f1c8d.firebaseapp.com',
    storageBucket: 'codequest-f1c8d.firebasestorage.app',
    measurementId: 'G-ZNTNPKH0YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6OziMFbeJfGX5hE7DoBn2sLXdye3pFT0',
    appId: '1:377438843224:android:b7b278a0d6aa8e21df752d',
    messagingSenderId: '377438843224',
    projectId: 'codequest-f1c8d',
    storageBucket: 'codequest-f1c8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnXMX31dwfKp7yhSKmiaaeNlda33vaAk',
    appId: '1:377438843224:ios:797bde72e434e706df752d',
    messagingSenderId: '377438843224',
    projectId: 'codequest-f1c8d',
    storageBucket: 'codequest-f1c8d.firebasestorage.app',
    iosBundleId: 'com.example.codeQuestPre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbeRHIQZkihAXVoprt7YNYB9DbXn8h0d0',
    appId: '1:377438843224:web:c0783c977ea0b256df752d',
    messagingSenderId: '377438843224',
    projectId: 'codequest-f1c8d',
    authDomain: 'codequest-f1c8d.firebaseapp.com',
    storageBucket: 'codequest-f1c8d.firebasestorage.app',
    measurementId: 'G-PZCTTB23TW',
  );
}
